bp_frontend:
  name: "bp-frontend"
  replicaCount: 1
  labels:
    app: "bp-frontend"
  template:
    labels:
      app: "bp-frontend"
  container:
    name: bp-frontend
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/app/bp/dev-frontend
    imageTag: latest
    imagePullPolicy: "Always"
  profiles: "container"
  service:
    name: "frontend"
    type: ClusterIP
    port: 80
    targetPort: 80
